/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutViewProfileIndexRouteImport } from './routes/_layout/view-profile/index'
import { Route as LayoutUsersIndexRouteImport } from './routes/_layout/users/index'
import { Route as LayoutTasksIndexRouteImport } from './routes/_layout/tasks/index'
import { Route as LayoutProjectsIndexRouteImport } from './routes/_layout/projects/index'
import { Route as LayoutDashboardIndexRouteImport } from './routes/_layout/dashboard/index'
import { Route as LayoutUsersAdduserIndexRouteImport } from './routes/_layout/users/adduser/index'
import { Route as LayoutTasksAddIndexRouteImport } from './routes/_layout/tasks/add/index'
import { Route as LayoutProjectsAddIndexRouteImport } from './routes/_layout/projects/add/index'
import { Route as LayoutProjectsIdIndexRouteImport } from './routes/_layout/projects/$id/index'
import { Route as LayoutUsersEditIdIndexRouteImport } from './routes/_layout/users/edit/$id/index'
import { Route as LayoutTasksViewIdIndexRouteImport } from './routes/_layout/tasks/view/$id/index'
import { Route as LayoutTasksEditIdIndexRouteImport } from './routes/_layout/tasks/edit/$id/index'
import { Route as LayoutProjectsEditIdIndexRouteImport } from './routes/_layout/projects/edit/$id/index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutViewProfileIndexRoute = LayoutViewProfileIndexRouteImport.update({
  id: '/view-profile/',
  path: '/view-profile/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersIndexRoute = LayoutUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTasksIndexRoute = LayoutTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsIndexRoute = LayoutProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardIndexRoute = LayoutDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersAdduserIndexRoute = LayoutUsersAdduserIndexRouteImport.update({
  id: '/users/adduser/',
  path: '/users/adduser/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTasksAddIndexRoute = LayoutTasksAddIndexRouteImport.update({
  id: '/tasks/add/',
  path: '/tasks/add/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsAddIndexRoute = LayoutProjectsAddIndexRouteImport.update({
  id: '/projects/add/',
  path: '/projects/add/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsIdIndexRoute = LayoutProjectsIdIndexRouteImport.update({
  id: '/projects/$id/',
  path: '/projects/$id/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersEditIdIndexRoute = LayoutUsersEditIdIndexRouteImport.update({
  id: '/users/edit/$id/',
  path: '/users/edit/$id/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTasksViewIdIndexRoute = LayoutTasksViewIdIndexRouteImport.update({
  id: '/tasks/view/$id/',
  path: '/tasks/view/$id/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTasksEditIdIndexRoute = LayoutTasksEditIdIndexRouteImport.update({
  id: '/tasks/edit/$id/',
  path: '/tasks/edit/$id/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsEditIdIndexRoute =
  LayoutProjectsEditIdIndexRouteImport.update({
    id: '/projects/edit/$id/',
    path: '/projects/edit/$id/',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof LayoutDashboardIndexRoute
  '/projects': typeof LayoutProjectsIndexRoute
  '/tasks': typeof LayoutTasksIndexRoute
  '/users': typeof LayoutUsersIndexRoute
  '/view-profile': typeof LayoutViewProfileIndexRoute
  '/projects/$id': typeof LayoutProjectsIdIndexRoute
  '/projects/add': typeof LayoutProjectsAddIndexRoute
  '/tasks/add': typeof LayoutTasksAddIndexRoute
  '/users/adduser': typeof LayoutUsersAdduserIndexRoute
  '/projects/edit/$id': typeof LayoutProjectsEditIdIndexRoute
  '/tasks/edit/$id': typeof LayoutTasksEditIdIndexRoute
  '/tasks/view/$id': typeof LayoutTasksViewIdIndexRoute
  '/users/edit/$id': typeof LayoutUsersEditIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof LayoutDashboardIndexRoute
  '/projects': typeof LayoutProjectsIndexRoute
  '/tasks': typeof LayoutTasksIndexRoute
  '/users': typeof LayoutUsersIndexRoute
  '/view-profile': typeof LayoutViewProfileIndexRoute
  '/projects/$id': typeof LayoutProjectsIdIndexRoute
  '/projects/add': typeof LayoutProjectsAddIndexRoute
  '/tasks/add': typeof LayoutTasksAddIndexRoute
  '/users/adduser': typeof LayoutUsersAdduserIndexRoute
  '/projects/edit/$id': typeof LayoutProjectsEditIdIndexRoute
  '/tasks/edit/$id': typeof LayoutTasksEditIdIndexRoute
  '/tasks/view/$id': typeof LayoutTasksViewIdIndexRoute
  '/users/edit/$id': typeof LayoutUsersEditIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/dashboard/': typeof LayoutDashboardIndexRoute
  '/_layout/projects/': typeof LayoutProjectsIndexRoute
  '/_layout/tasks/': typeof LayoutTasksIndexRoute
  '/_layout/users/': typeof LayoutUsersIndexRoute
  '/_layout/view-profile/': typeof LayoutViewProfileIndexRoute
  '/_layout/projects/$id/': typeof LayoutProjectsIdIndexRoute
  '/_layout/projects/add/': typeof LayoutProjectsAddIndexRoute
  '/_layout/tasks/add/': typeof LayoutTasksAddIndexRoute
  '/_layout/users/adduser/': typeof LayoutUsersAdduserIndexRoute
  '/_layout/projects/edit/$id/': typeof LayoutProjectsEditIdIndexRoute
  '/_layout/tasks/edit/$id/': typeof LayoutTasksEditIdIndexRoute
  '/_layout/tasks/view/$id/': typeof LayoutTasksViewIdIndexRoute
  '/_layout/users/edit/$id/': typeof LayoutUsersEditIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/projects'
    | '/tasks'
    | '/users'
    | '/view-profile'
    | '/projects/$id'
    | '/projects/add'
    | '/tasks/add'
    | '/users/adduser'
    | '/projects/edit/$id'
    | '/tasks/edit/$id'
    | '/tasks/view/$id'
    | '/users/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/projects'
    | '/tasks'
    | '/users'
    | '/view-profile'
    | '/projects/$id'
    | '/projects/add'
    | '/tasks/add'
    | '/users/adduser'
    | '/projects/edit/$id'
    | '/tasks/edit/$id'
    | '/tasks/view/$id'
    | '/users/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/dashboard/'
    | '/_layout/projects/'
    | '/_layout/tasks/'
    | '/_layout/users/'
    | '/_layout/view-profile/'
    | '/_layout/projects/$id/'
    | '/_layout/projects/add/'
    | '/_layout/tasks/add/'
    | '/_layout/users/adduser/'
    | '/_layout/projects/edit/$id/'
    | '/_layout/tasks/edit/$id/'
    | '/_layout/tasks/view/$id/'
    | '/_layout/users/edit/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/view-profile/': {
      id: '/_layout/view-profile/'
      path: '/view-profile'
      fullPath: '/view-profile'
      preLoaderRoute: typeof LayoutViewProfileIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users/': {
      id: '/_layout/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tasks/': {
      id: '/_layout/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof LayoutTasksIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/': {
      id: '/_layout/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/': {
      id: '/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users/adduser/': {
      id: '/_layout/users/adduser/'
      path: '/users/adduser'
      fullPath: '/users/adduser'
      preLoaderRoute: typeof LayoutUsersAdduserIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tasks/add/': {
      id: '/_layout/tasks/add/'
      path: '/tasks/add'
      fullPath: '/tasks/add'
      preLoaderRoute: typeof LayoutTasksAddIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/add/': {
      id: '/_layout/projects/add/'
      path: '/projects/add'
      fullPath: '/projects/add'
      preLoaderRoute: typeof LayoutProjectsAddIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$id/': {
      id: '/_layout/projects/$id/'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof LayoutProjectsIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users/edit/$id/': {
      id: '/_layout/users/edit/$id/'
      path: '/users/edit/$id'
      fullPath: '/users/edit/$id'
      preLoaderRoute: typeof LayoutUsersEditIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tasks/view/$id/': {
      id: '/_layout/tasks/view/$id/'
      path: '/tasks/view/$id'
      fullPath: '/tasks/view/$id'
      preLoaderRoute: typeof LayoutTasksViewIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tasks/edit/$id/': {
      id: '/_layout/tasks/edit/$id/'
      path: '/tasks/edit/$id'
      fullPath: '/tasks/edit/$id'
      preLoaderRoute: typeof LayoutTasksEditIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/edit/$id/': {
      id: '/_layout/projects/edit/$id/'
      path: '/projects/edit/$id'
      fullPath: '/projects/edit/$id'
      preLoaderRoute: typeof LayoutProjectsEditIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutDashboardIndexRoute: typeof LayoutDashboardIndexRoute
  LayoutProjectsIndexRoute: typeof LayoutProjectsIndexRoute
  LayoutTasksIndexRoute: typeof LayoutTasksIndexRoute
  LayoutUsersIndexRoute: typeof LayoutUsersIndexRoute
  LayoutViewProfileIndexRoute: typeof LayoutViewProfileIndexRoute
  LayoutProjectsIdIndexRoute: typeof LayoutProjectsIdIndexRoute
  LayoutProjectsAddIndexRoute: typeof LayoutProjectsAddIndexRoute
  LayoutTasksAddIndexRoute: typeof LayoutTasksAddIndexRoute
  LayoutUsersAdduserIndexRoute: typeof LayoutUsersAdduserIndexRoute
  LayoutProjectsEditIdIndexRoute: typeof LayoutProjectsEditIdIndexRoute
  LayoutTasksEditIdIndexRoute: typeof LayoutTasksEditIdIndexRoute
  LayoutTasksViewIdIndexRoute: typeof LayoutTasksViewIdIndexRoute
  LayoutUsersEditIdIndexRoute: typeof LayoutUsersEditIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutDashboardIndexRoute: LayoutDashboardIndexRoute,
  LayoutProjectsIndexRoute: LayoutProjectsIndexRoute,
  LayoutTasksIndexRoute: LayoutTasksIndexRoute,
  LayoutUsersIndexRoute: LayoutUsersIndexRoute,
  LayoutViewProfileIndexRoute: LayoutViewProfileIndexRoute,
  LayoutProjectsIdIndexRoute: LayoutProjectsIdIndexRoute,
  LayoutProjectsAddIndexRoute: LayoutProjectsAddIndexRoute,
  LayoutTasksAddIndexRoute: LayoutTasksAddIndexRoute,
  LayoutUsersAdduserIndexRoute: LayoutUsersAdduserIndexRoute,
  LayoutProjectsEditIdIndexRoute: LayoutProjectsEditIdIndexRoute,
  LayoutTasksEditIdIndexRoute: LayoutTasksEditIdIndexRoute,
  LayoutTasksViewIdIndexRoute: LayoutTasksViewIdIndexRoute,
  LayoutUsersEditIdIndexRoute: LayoutUsersEditIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
